### ISSUE TITLE
Repeated wizards in query result

### ISSUE THREAD

**Issue by niftyminer** [tv3636/forgotten-market#1]
querying for origin=Tower gave me a result with identical wizards, consistently:

https://forgotten.market/0x521f9c7505005cfa19a8e5786a9c3c9c9f5e6f42?origin=Tower

<img width="616" alt="Screenshot 2022-02-24 at 12 46 31" src="https://user-images.githubusercontent.com/2270661/155518206-768d32b9-2740-4cba-a9e1-5637618a4274.png">

**Comment by tv3636** [comment]
hmm not able to reproduce now - I think this might be due to the API responses from Reservoir sometimes having a token in multiple pages of the response, let me check with the team and also see if I can add something on the client to dedup. thanks for sharing this!

**Comment by niftyminer** [comment]
I have it with the ponies too. I see several `https://mainnet-api-v4.reservoir.tools/tokens?contract=0xf55b615b479482440135ebf1b907fd4c37ed9420&offset=20` calls (expected), but more than one of them returns pony `34`, so you're assumption is correct 👍

**Comment by MerchantPeppy** [comment]
Heh, just came to report this. Might take a stab at dedup.

**Comment by tv3636** [comment]
believe this is resolved now - if you happen to see it again please feel free to open a new issue
